"""
Database Read/Write Operations (CRUD Layer)

This file contains all the functions that read from and write to the database.
CRUD stands for Create, Read, Update, Delete — the four basic operations you
can do with stored data.

Instead of writing raw SQL queries, these functions use SQLAlchemy (a Python
library) to build queries in Python code. Each function opens a short-lived
database session (a connection), performs the operation, and then closes it.

Key patterns used throughout this file:

1. SessionLocal() — Opens a new database connection. Used inside a "with"
   block so the connection is automatically closed when done, even if an
   error occurs.

2. db.add(obj) + db.commit() — Inserts a new row (add) and saves the change
   permanently (commit). If something goes wrong, the "with" block ensures
   the session is rolled back (undone) automatically.

3. db.refresh(obj) — After committing, re-reads the object from the database
   to pick up any values that were generated by the database itself (like
   auto-incrementing IDs or default timestamps).

4. db.get(Model, id) — Fetches a single row by its primary key. Returns
   None if no matching row exists.

5. select(Model).where(...) — Builds a SQL SELECT query with filters.
   .scalars() converts the raw database rows into Python objects.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional
from uuid import uuid4

from sqlalchemy import and_, func, select

from app.db.models import Approval, AuditLog, Document, IngestJob, Tenant, TenantPolicy, User, UserTenant
from app.db.session import Base, SessionLocal, engine


def utcnow_naive() -> datetime:
    """Return the current UTC time without timezone info.

    This is a helper used to stamp "updated_at" and "decided_at" fields
    when modifying records. It matches the same function in models.py.
    """
    return datetime.now(timezone.utc).replace(tzinfo=None)


# ── Database Initialization ───────────────────────────────────────────

def init_db() -> None:
    """Create all database tables if they don't already exist.

    This reads the table definitions from models.py and issues CREATE TABLE
    statements for any tables that are missing. This is a convenience for
    development and testing. In production, you should use Alembic
    (a migration tool) to manage schema changes safely.
    """
    Base.metadata.create_all(bind=engine)


# ── Audit Log Operations ─────────────────────────────────────────────

def insert_log(
    *,
    tenant_id: str,
    user: str,
    action: str,
    input_text: str,
    output_text: str,
    metadata: str,
) -> None:
    """Write one entry to the audit log.

    This is called whenever something important happens (a question is asked,
    a document is uploaded, etc.). The log is append-only — entries are never
    modified or deleted, ensuring a reliable compliance trail.

    All parameters are keyword-only (the * in the signature) to prevent
    accidentally mixing up arguments.
    """
    with SessionLocal() as db:
        db.add(
            AuditLog(
                tenant_id=tenant_id,
                user=user,
                action=action,
                input_text=input_text,
                output_text=output_text,
                meta_json=metadata,
            )
        )
        db.commit()


def list_logs(*, tenant_ids: list[str], limit: int = 100) -> list[AuditLog]:
    """Fetch the most recent audit log entries for the given tenants.

    Returns up to 'limit' rows, sorted newest-first. The tenant_ids filter
    ensures users only see logs from tenants they have access to.
    """
    with SessionLocal() as db:
        # Build a query: SELECT * FROM audit_logs
        #   WHERE tenant_id IN (:tenant_ids)
        #   ORDER BY id DESC   (newest first)
        #   LIMIT :limit
        query = select(AuditLog).where(AuditLog.tenant_id.in_(tenant_ids)).order_by(AuditLog.id.desc()).limit(limit)
        return list(db.execute(query).scalars())


def search_logs(
    *,
    tenant_ids: list[str],
    username: Optional[str],
    action: Optional[str],
    start_time: Optional[datetime],
    end_time: Optional[datetime],
    limit: int,
) -> list[AuditLog]:
    """Search audit logs with optional filters for user, action, and time range.

    This builds the query dynamically — only the filters that are provided
    (not None) are added to the WHERE clause. This lets the caller search
    by any combination of criteria.
    """
    with SessionLocal() as db:
        # Start with: SELECT * FROM audit_logs WHERE tenant_id IN (...)
        query = select(AuditLog).where(AuditLog.tenant_id.in_(tenant_ids))
        # Optionally narrow down by specific user
        if username:
            query = query.where(AuditLog.user == username)
        # Optionally narrow down by action type (e.g., "query", "login")
        if action:
            query = query.where(AuditLog.action == action)
        # Optionally narrow down to entries after a start time
        if start_time:
            query = query.where(AuditLog.timestamp >= start_time)
        # Optionally narrow down to entries before an end time
        if end_time:
            query = query.where(AuditLog.timestamp <= end_time)
        # Always sort newest-first and cap the number of results
        query = query.order_by(AuditLog.id.desc()).limit(limit)
        return list(db.execute(query).scalars())


# ── Tenant Operations ─────────────────────────────────────────────────

def create_tenant(*, tenant_id: str, name: str) -> Tenant:
    """Create a new tenant (organization/workspace) in the database.

    Returns the newly created Tenant object with all fields populated
    (including the auto-generated created_at timestamp).
    """
    with SessionLocal() as db:
        tenant = Tenant(tenant_id=tenant_id, name=name)
        db.add(tenant)
        db.commit()
        db.refresh(tenant)
        return tenant


def list_tenants() -> list[Tenant]:
    """Return all tenants, sorted newest-first.

    This is typically used by system administrators to see all
    organizations registered in the platform.
    """
    with SessionLocal() as db:
        return list(db.execute(select(Tenant).order_by(Tenant.created_at.desc())).scalars())


def get_tenant(tenant_id: str) -> Optional[Tenant]:
    """Look up a single tenant by its ID. Returns None if not found."""
    with SessionLocal() as db:
        return db.get(Tenant, tenant_id)


# ── User Operations ───────────────────────────────────────────────────

def create_user(
    *,
    user_id: str,
    username: str,
    password_hash: str,
    role: str,
    default_tenant_id: Optional[str],
) -> User:
    """Create a new user account in the database.

    The password should already be hashed before calling this function —
    we never store plain-text passwords. Returns the newly created User.
    """
    with SessionLocal() as db:
        user = User(
            user_id=user_id,
            username=username,
            password_hash=password_hash,
            role=role,
            default_tenant_id=default_tenant_id,
        )
        db.add(user)
        db.commit()
        db.refresh(user)
        return user


def get_user_by_username(username: str) -> Optional[User]:
    """Find a user by their login name. Returns None if no match.

    This is used during login to look up the user's stored password hash
    for verification.
    """
    with SessionLocal() as db:
        return db.execute(select(User).where(User.username == username)).scalar_one_or_none()


def get_user_by_id(user_id: str) -> Optional[User]:
    """Find a user by their unique ID. Returns None if not found."""
    with SessionLocal() as db:
        return db.get(User, user_id)


def list_users() -> list[User]:
    """Return all user accounts, sorted newest-first.

    Typically used by administrators for user management.
    """
    with SessionLocal() as db:
        return list(db.execute(select(User).order_by(User.created_at.desc())).scalars())


# ── User-Tenant Assignment Operations ─────────────────────────────────

def assign_user_tenant(*, user_id: str, tenant_id: str) -> UserTenant:
    """Grant a user access to a tenant. If already assigned, return the existing link.

    This is idempotent — calling it twice with the same user and tenant
    has no side effect. It first checks if the link already exists to
    avoid creating duplicates.
    """
    with SessionLocal() as db:
        # Check if this user-tenant link already exists
        existing = db.execute(
            select(UserTenant).where(and_(UserTenant.user_id == user_id, UserTenant.tenant_id == tenant_id))
        ).scalar_one_or_none()
        if existing:
            return existing
        # Create a new link between the user and the tenant
        link = UserTenant(user_id=user_id, tenant_id=tenant_id)
        db.add(link)
        db.commit()
        db.refresh(link)
        return link


def list_user_tenants(user_id: str) -> list[UserTenant]:
    """Return all tenant links for a given user.

    This tells you which tenants (workspaces) a user has access to.
    """
    with SessionLocal() as db:
        return list(db.execute(select(UserTenant).where(UserTenant.user_id == user_id)).scalars())


def user_has_tenant(*, user_id: str, tenant_id: str) -> bool:
    """Check whether a user has access to a specific tenant.

    Returns True if the link exists, False otherwise. Used for
    authorization checks — ensuring a user can only access data
    in tenants they belong to.
    """
    with SessionLocal() as db:
        row = db.execute(
            select(UserTenant).where(and_(UserTenant.user_id == user_id, UserTenant.tenant_id == tenant_id))
        ).scalar_one_or_none()
        return row is not None


# ── Approval Operations ───────────────────────────────────────────────

def create_approval(
    *,
    approval_id: str,
    user_id: str,
    tenant_id: str,
    question: str,
    draft_answer: str,
) -> Approval:
    """Create a new approval request for an AI-generated answer.

    When the system determines that an answer needs human review (based
    on tenant policy or document sensitivity), it calls this function to
    queue the answer for review. The status starts as "pending".
    """
    with SessionLocal() as db:
        approval = Approval(
            approval_id=approval_id,
            user_id=user_id,
            tenant_id=tenant_id,
            question=question,
            draft_answer=draft_answer,
            status="pending",
        )
        db.add(approval)
        db.commit()
        db.refresh(approval)
        return approval


def list_approvals(*, tenant_ids: list[str], status: Optional[str], limit: int) -> list[Approval]:
    """List approval requests for given tenants, optionally filtered by status.

    If status is provided (e.g., "pending"), only matching approvals are
    returned. Results are sorted newest-first.
    """
    with SessionLocal() as db:
        query = select(Approval).where(Approval.tenant_id.in_(tenant_ids))
        if status:
            query = query.where(Approval.status == status)
        query = query.order_by(Approval.created_at.desc()).limit(limit)
        return list(db.execute(query).scalars())


def get_approval(approval_id: str) -> Optional[Approval]:
    """Fetch a single approval request by its ID. Returns None if not found."""
    with SessionLocal() as db:
        return db.get(Approval, approval_id)


def update_approval(
    *,
    approval_id: str,
    status: str,
    decision_by: str,
    decision_note: str,
    final_answer: Optional[str],
) -> Optional[Approval]:
    """Record a reviewer's decision on an approval request.

    Sets the status to "approved" or "rejected", records who made the
    decision and when, and optionally stores an edited final answer.
    Returns None if the approval_id does not exist.
    """
    with SessionLocal() as db:
        approval = db.get(Approval, approval_id)
        if not approval:
            return None
        approval.status = status
        approval.decision_by = decision_by
        approval.decision_note = decision_note
        approval.decided_at = utcnow_naive()
        approval.final_answer = final_answer
        db.commit()
        db.refresh(approval)
        return approval


# ── Ingest Job Operations ─────────────────────────────────────────────

def create_ingest_job(*, job_id: str, tenant_id: str, created_by: str, filename: str) -> IngestJob:
    """Create a new document ingestion job with status "queued".

    Called when a user uploads a file. The background worker will pick up
    queued jobs, process the file, and update the status accordingly.
    """
    with SessionLocal() as db:
        job = IngestJob(job_id=job_id, tenant_id=tenant_id, created_by=created_by, filename=filename, status="queued")
        db.add(job)
        db.commit()
        db.refresh(job)
        return job


def update_ingest_job(
    *,
    job_id: str,
    status: str,
    chunks_indexed: int = 0,
    document_id: Optional[str] = None,
    error_message: Optional[str] = None,
) -> Optional[IngestJob]:
    """Update the progress or final result of a document ingestion job.

    Called by the background worker to report progress (chunks_indexed),
    completion (status="done", document_id set), or failure (status="failed",
    error_message set). Returns None if the job_id does not exist.
    """
    with SessionLocal() as db:
        job = db.get(IngestJob, job_id)
        if not job:
            return None
        job.status = status
        job.chunks_indexed = chunks_indexed
        job.document_id = document_id
        job.error_message = error_message
        job.updated_at = utcnow_naive()
        db.commit()
        db.refresh(job)
        return job


def get_ingest_job(job_id: str) -> Optional[IngestJob]:
    """Fetch a single ingestion job by its ID. Returns None if not found."""
    with SessionLocal() as db:
        return db.get(IngestJob, job_id)


def list_ingest_jobs(*, tenant_ids: list[str], limit: int) -> list[IngestJob]:
    """List recent ingestion jobs for given tenants, sorted newest-first.

    Used by the UI to show the status of recent document uploads.
    """
    with SessionLocal() as db:
        query = select(IngestJob).where(IngestJob.tenant_id.in_(tenant_ids)).order_by(IngestJob.created_at.desc()).limit(limit)
        return list(db.execute(query).scalars())


# ── Document CRUD ──────────────────────────────────────────────────────

def create_document_record(
    *,
    document_id: str,
    tenant_id: str,
    filename: str,
    mime_type: str,
    file_size: int,
    page_count: int,
    chunk_count: int,
    created_by: str,
    storage_path: str | None = None,
    sensitivity: str = "normal",
) -> Document:
    """Create a new document record after successful ingestion.

    Called by the ingestion pipeline once a file has been parsed, chunked,
    and indexed. Stores all the metadata about the document so it can be
    found, filtered, and managed through the UI.
    """
    with SessionLocal() as db:
        doc = Document(
            document_id=document_id,
            tenant_id=tenant_id,
            filename=filename,
            mime_type=mime_type,
            file_size=file_size,
            page_count=page_count,
            chunk_count=chunk_count,
            created_by=created_by,
            storage_path=storage_path,
            sensitivity=sensitivity,
        )
        db.add(doc)
        db.commit()
        db.refresh(doc)
        return doc


def get_document(document_id: str) -> Document | None:
    """Fetch a single document by its ID. Returns None if not found."""
    with SessionLocal() as db:
        return db.get(Document, document_id)


def list_documents_db(
    *,
    tenant_id: str,
    status: str | None = "active",
    sensitivity: str | None = None,
    limit: int = 100,
    offset: int = 0,
) -> tuple[list[Document], int]:
    """List documents for a tenant with optional filters and pagination.

    Returns a tuple of (documents, total_count). The total_count is the
    number of matching documents BEFORE applying limit/offset, which is
    needed by the UI to show "page 2 of 5" style pagination.

    By default, only "active" documents are returned (not archived/deleted).
    """
    with SessionLocal() as db:
        # Build the main query to fetch document rows
        query = select(Document).where(Document.tenant_id == tenant_id)
        # Build a parallel COUNT query to get the total number of matches
        # (needed for pagination — e.g., "showing 10 of 42 documents")
        count_query = select(func.count()).select_from(Document).where(Document.tenant_id == tenant_id)
        # Apply optional status filter to both queries
        if status:
            query = query.where(Document.status == status)
            count_query = count_query.where(Document.status == status)
        # Apply optional sensitivity filter to both queries
        if sensitivity:
            query = query.where(Document.sensitivity == sensitivity)
            count_query = count_query.where(Document.sensitivity == sensitivity)
        # Execute the count query first to get the total
        total = db.execute(count_query).scalar() or 0
        # Then fetch the actual page of results, sorted newest-first
        query = query.order_by(Document.created_at.desc()).offset(offset).limit(limit)
        docs = list(db.execute(query).scalars())
        return docs, total


def update_document_db(
    *,
    document_id: str,
    sensitivity: str | None = None,
    status: str | None = None,
    approval_override: str | None = "__unset__",
) -> Document | None:
    """Update a document's sensitivity, status, or approval override.

    Returns the updated document, or None if the document_id was not found.

    The approval_override parameter uses a special sentinel value "__unset__"
    to distinguish between two different intentions:
      - approval_override="__unset__" means "don't change this field at all"
        (the caller didn't provide a value).
      - approval_override=None means "clear this field" (set it to NULL in
        the database, removing any per-document override).
      - approval_override="always" or "none" means "set this specific value".

    We can't use None alone for "don't change" because None is a valid value
    we might want to SET (to clear the override). The "__unset__" string
    solves this ambiguity.
    """
    with SessionLocal() as db:
        doc = db.get(Document, document_id)
        if not doc:
            return None
        if sensitivity is not None:
            doc.sensitivity = sensitivity
        if status is not None:
            doc.status = status
        # Only update approval_override if the caller explicitly provided a value
        # (i.e., it's not the "__unset__" sentinel)
        if approval_override != "__unset__":
            doc.approval_override = approval_override
        doc.updated_at = utcnow_naive()
        db.commit()
        db.refresh(doc)
        return doc


def bulk_update_documents_db(
    *,
    document_ids: list[str],
    tenant_id: str,
    sensitivity: str | None = None,
    status: str | None = None,
) -> int:
    """Update multiple documents at once (batch operation).

    Only updates documents that match BOTH the given IDs AND the tenant_id.
    The tenant_id check is a security measure — it prevents a user from
    modifying documents that belong to a different tenant, even if they
    somehow know the document IDs.

    Returns the number of documents that were actually updated.
    """
    with SessionLocal() as db:
        # Find all documents matching the given IDs AND belonging to this tenant
        query = select(Document).where(
            and_(Document.document_id.in_(document_ids), Document.tenant_id == tenant_id)
        )
        docs = list(db.execute(query).scalars())
        # Apply the requested changes to each matching document
        for doc in docs:
            if sensitivity is not None:
                doc.sensitivity = sensitivity
            if status is not None:
                doc.status = status
            doc.updated_at = utcnow_naive()
        db.commit()
        return len(docs)


def get_documents_by_ids(document_ids: list[str]) -> list[Document]:
    """Fetch multiple documents by their IDs in a single query.

    Returns an empty list if no IDs are provided (avoids an unnecessary
    database call). Used when you already have a list of document IDs
    (e.g., from search results) and need the full document details.
    """
    if not document_ids:
        return []
    with SessionLocal() as db:
        query = select(Document).where(Document.document_id.in_(document_ids))
        return list(db.execute(query).scalars())


# ── TenantPolicy CRUD ──────────────────────────────────────────────────

def get_tenant_policy(tenant_id: str) -> TenantPolicy | None:
    """Fetch the approval policy for a tenant. Returns None if no policy is set."""
    with SessionLocal() as db:
        return db.get(TenantPolicy, tenant_id)


def upsert_tenant_policy(
    *,
    tenant_id: str,
    approval_mode: str,
    updated_by: str,
) -> TenantPolicy:
    """Create or update the approval policy for a tenant.

    "Upsert" means: if a policy already exists for this tenant, update it;
    if not, create a new one. This avoids the need to check-then-create
    in the calling code.
    """
    with SessionLocal() as db:
        policy = db.get(TenantPolicy, tenant_id)
        if policy:
            # Policy exists — update it with the new values
            policy.approval_mode = approval_mode
            policy.updated_by = updated_by
            policy.updated_at = utcnow_naive()
        else:
            # No policy exists yet — create a new one
            policy = TenantPolicy(
                tenant_id=tenant_id,
                approval_mode=approval_mode,
                updated_by=updated_by,
            )
            db.add(policy)
        db.commit()
        db.refresh(policy)
        return policy


# ── Seed Data ──────────────────────────────────────────────────────────

def ensure_default_seed(*, demo_username: str, demo_password_hash: str, default_tenant_id: str) -> None:
    """Create default tenant and admin user if they don't already exist.

    This is called at application startup to ensure there is always at
    least one tenant and one admin user available for login. It is
    idempotent — running it multiple times has no side effect because
    it checks for existing records before creating new ones.

    The demo user is given the "admin" role and linked to the default tenant.
    """
    with SessionLocal() as db:
        # Create the default tenant if it doesn't exist yet
        tenant = db.get(Tenant, default_tenant_id)
        if not tenant:
            tenant = Tenant(tenant_id=default_tenant_id, name="Default Tenant")
            db.add(tenant)

        # Create the demo admin user if they don't exist yet
        user = db.execute(select(User).where(User.username == demo_username)).scalar_one_or_none()
        if not user:
            user_id = str(uuid4())
            user = User(
                user_id=user_id,
                username=demo_username,
                password_hash=demo_password_hash,
                role="admin",
                default_tenant_id=default_tenant_id,
            )
            db.add(user)
            # Also link the new user to the default tenant so they can access it
            db.add(UserTenant(user_id=user_id, tenant_id=default_tenant_id))

        db.commit()
