"""Prometheus metrics for monitoring system health and performance.

This module defines all the Prometheus metric objects used across the application.
Prometheus is an open-source monitoring tool that collects numeric measurements
over time (e.g., "how many requests happened?" or "how long did they take?").

There are three main metric types used here:
  - Counter: a number that only goes up (e.g., total requests served).
  - Histogram: records values (e.g., response times) and groups them into
    configurable buckets so you can see the distribution.
  - Gauge: a number that can go up or down (e.g., current queue depth).

The MetricsMiddleware class automatically records HTTP request counts and
latencies for every incoming request, without any changes to route handlers.
"""

import time
from typing import Callable

from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

from app.core.config import settings
from app.services.queue import get_redis_connection

# --- HTTP Request Metrics ---
# These metrics track every HTTP request that reaches the server.
# They help answer questions like "How many 500 errors happened today?"
# and "Are response times getting slower?"

# Counts the total number of HTTP requests, broken down by HTTP method
# (GET, POST, etc.), URL path, and response status code (200, 404, 500, etc.).
# Useful for spotting error spikes or traffic surges.
REQUEST_COUNT = Counter(
    "http_requests_total",
    "Total HTTP requests",
    ["method", "path", "status"],
)
# Records how long each HTTP request takes to complete, in seconds.
# The "buckets" define the time ranges (10ms, 25ms, ... 10s) used to group
# measurements, so you can see what percentage of requests finish within
# a given time window.
REQUEST_LATENCY = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency in seconds",
    ["method", "path"],
    buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
)
# Shows how many documents are currently waiting in the ingestion queue.
# A steadily growing number here means the system is falling behind on
# processing uploaded documents.
INGEST_QUEUE_DEPTH = Gauge(
    "ingest_queue_depth",
    "Current depth of the ingest queue",
)

# --- LLM (Large Language Model) Metrics ---
# These metrics track calls to external AI providers (e.g., OpenAI, Anthropic).
# LLM calls are the most expensive and slowest operations in the system, so
# monitoring them closely is critical.

# Records how long each LLM call takes, broken down by provider and operation.
# Buckets go up to 60 seconds because LLM calls can be very slow.
LLM_CALL_DURATION = Histogram(
    "llm_call_duration_seconds",
    "LLM call latency in seconds",
    ["provider", "operation"],
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0),
)
# Counts how many LLM calls failed (e.g., timeouts, rate limits, API errors).
# A sudden spike here usually means the LLM provider is having issues.
LLM_CALL_ERRORS = Counter(
    "llm_call_errors_total",
    "Total LLM call errors",
    ["provider", "operation"],
)
# Tracks the approximate number of tokens (words/word-pieces) generated by
# the LLM. This is important for cost monitoring because LLM providers
# charge per token.
LLM_TOKENS_GENERATED = Counter(
    "llm_tokens_generated_total",
    "Approximate number of LLM tokens generated (streaming chunks)",
    ["provider"],
)

# --- Embedding Metrics ---
# Embeddings convert text into numeric vectors so they can be compared for
# similarity. These metrics track the performance of that conversion step.

# Records how long each embedding call takes, by provider.
EMBEDDING_DURATION = Histogram(
    "embedding_duration_seconds",
    "Embedding call latency in seconds",
    ["provider"],
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0),
)
# Counts the total number of text passages that have been converted into
# embeddings. Helps track usage volume against provider quotas or budgets.
EMBEDDING_TEXTS_PROCESSED = Counter(
    "embedding_texts_processed_total",
    "Total number of texts embedded",
    ["provider"],
)

# --- RAG (Retrieval-Augmented Generation) Pipeline Metrics ---
# RAG is the core workflow: retrieve relevant document chunks from the
# vector database, then feed them to the LLM to generate an answer.
# These metrics cover the full pipeline.

# Counts the total number of RAG queries, labeled by outcome (success/failure).
RAG_QUERY_TOTAL = Counter(
    "rag_query_total",
    "Total RAG queries processed",
    ["status"],
)
# Records the end-to-end time for a full RAG query (retrieval + generation).
RAG_QUERY_DURATION = Histogram(
    "rag_query_duration_seconds",
    "End-to-end RAG query duration in seconds",
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0),
)
# Records how long just the vector-database search step takes, by search type.
RETRIEVAL_DURATION = Histogram(
    "retrieval_duration_seconds",
    "Vector search duration in seconds",
    ["search_type"],
    buckets=(0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5),
)
# Records how many document chunks each search returns. If searches
# consistently return 0 results, the knowledge base may be missing content.
RETRIEVAL_RESULTS_COUNT = Histogram(
    "retrieval_results_count",
    "Number of chunks returned per search",
    buckets=(0, 1, 2, 3, 4, 5, 10, 20),
)

# --- Ingestion Metrics ---
# Ingestion is the process of uploading documents, splitting them into
# chunks, and storing their embeddings. These metrics track that pipeline.

# Counts the total number of documents ingested, by file type and outcome.
DOCUMENT_INGEST_TOTAL = Counter(
    "document_ingest_total",
    "Total documents ingested",
    ["file_type", "status"],
)
# Records how long it takes to fully ingest a document, by file type.
DOCUMENT_INGEST_DURATION = Histogram(
    "document_ingest_duration_seconds",
    "Document ingestion duration in seconds",
    ["file_type"],
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0),
)
# Counts the total number of text chunks produced during ingestion.
# A single document may produce many chunks.
CHUNKS_PRODUCED_TOTAL = Counter(
    "chunks_produced_total",
    "Total number of chunks produced during ingestion",
)

# --- Policy & Approval Metrics ---
# The system can evaluate LLM outputs against compliance policies and may
# require human approval for sensitive answers. These metrics track that.

# Counts policy evaluation outcomes (e.g., "pass", "fail", "flagged").
POLICY_EVALUATIONS_TOTAL = Counter(
    "policy_evaluations_total",
    "Total output policy evaluations",
    ["result"],
)
# Counts how many times a human-approval request was created.
APPROVAL_REQUESTS_TOTAL = Counter(
    "approval_requests_total",
    "Total approval requests created",
)

# --- System-Level Metrics ---
# High-level indicators of overall system health.

# Tracks the number of distinct tenants (organizations) that have made
# queries recently. Useful for understanding active usage.
ACTIVE_TENANTS = Gauge(
    "active_tenants",
    "Number of active tenants (from recent queries)",
)
# Reports the health status of individual components (database, Redis, etc.).
# 1 means healthy, 0 means unhealthy. Monitoring dashboards can alert when
# any component drops to 0.
HEALTH_CHECK_STATUS = Gauge(
    "health_check_status",
    "Health check status (1=healthy, 0=unhealthy)",
    ["component"],
)


def _route_path(request: Request) -> str:
    """Extract the route template path from a request.

    Prefers the route template (e.g., "/items/{id}") over the actual URL
    path (e.g., "/items/42") so that metrics are grouped by endpoint
    rather than creating a separate time series for every unique URL.
    """
    route = request.scope.get("route")
    if route and hasattr(route, "path"):
        return route.path
    return request.url.path


class MetricsMiddleware(BaseHTTPMiddleware):
    """Middleware that automatically records HTTP metrics for every request.

    Middleware is code that runs before and after every HTTP request,
    without the route handler needing to know about it. This middleware:
      1. Records the time when a request arrives.
      2. Lets the request proceed through to the actual route handler.
      3. After the response is ready, calculates how long the request took.
      4. Updates the REQUEST_COUNT and REQUEST_LATENCY Prometheus metrics.

    This gives us automatic performance monitoring for every endpoint
    with zero changes to the route handler code.
    """

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        # Record the start time using a high-precision clock
        start_time = time.perf_counter()
        # Pass the request to the next handler in the chain (the actual route)
        response = await call_next(request)
        # Calculate how many seconds the request took
        duration = time.perf_counter() - start_time

        # Extract labels for the metric (method, path, status code)
        path = _route_path(request)
        method = request.method
        status = str(response.status_code)

        # Increment the request counter and record the latency observation
        REQUEST_COUNT.labels(method=method, path=path, status=status).inc()
        REQUEST_LATENCY.labels(method=method, path=path).observe(duration)

        return response


def metrics_response() -> Response:
    """Build and return the Prometheus metrics payload as an HTTP response.

    This function is called by the /metrics endpoint. Before generating
    the output, it also checks the Redis ingestion queue depth so that
    the INGEST_QUEUE_DEPTH gauge is up to date.
    """
    try:
        # Read the current length of the ingestion queue from Redis
        redis_conn = get_redis_connection()
        queue_depth = redis_conn.llen(f"rq:queue:{settings.ingest_queue_name}")
        INGEST_QUEUE_DEPTH.set(queue_depth)
    except Exception:
        # If Redis is down, skip updating the queue gauge but still return
        # all other metrics. The metrics endpoint should always stay available.
        pass

    # generate_latest() collects all registered Prometheus metrics and
    # formats them into the text format that Prometheus expects to scrape.
    payload = generate_latest()
    return Response(content=payload, media_type=CONTENT_TYPE_LATEST)
