"""Security headers middleware for defense-in-depth HTTP hardening.

Adds a set of standard security-related HTTP headers to every response.
These headers instruct the browser to enable various protections that
help prevent common web attacks such as clickjacking, MIME-type sniffing,
and information leakage through the Referer header.

This is a "defense-in-depth" measure — even if other security layers
fail, these headers provide an additional safety net at the browser level.
"""

from __future__ import annotations

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Middleware that attaches security headers to every HTTP response.

    Middleware is code that runs automatically before and after every request.
    This particular middleware waits for the response to be generated by the
    route handler, then adds protective headers before sending it to the client.
    """

    async def dispatch(self, request: Request, call_next):
        response: Response = await call_next(request)

        # X-Content-Type-Options: nosniff — prevents the browser from
        # guessing ("sniffing") the content type of a response. Without this,
        # a browser might interpret a plain-text file as JavaScript and
        # execute it, enabling cross-site scripting (XSS) attacks.
        response.headers["X-Content-Type-Options"] = "nosniff"

        # X-Frame-Options: DENY — prevents this page from being embedded
        # in an iframe on another website. This blocks "clickjacking" attacks
        # where an attacker overlays an invisible iframe to trick users into
        # clicking on hidden buttons.
        response.headers["X-Frame-Options"] = "DENY"

        # Referrer-Policy: strict-origin-when-cross-origin — controls how
        # much URL information the browser sends in the "Referer" header
        # when navigating to another site. This prevents leaking sensitive
        # URL paths (which might contain tokens or IDs) to third parties.
        response.headers["Referrer-Policy"] = "strict-origin-when-cross-origin"

        # Permissions-Policy — disables browser features that this API does
        # not need (geolocation, camera, microphone). Even if an attacker
        # injects malicious scripts, they cannot access these capabilities.
        response.headers["Permissions-Policy"] = "geolocation=(), camera=(), microphone=()"

        # Cache-Control: no-store — tells the browser and any intermediate
        # proxies to never cache this response. Important for API responses
        # that may contain sensitive or user-specific data; prevents stale
        # or confidential data from being served from a cache.
        response.headers["Cache-Control"] = "no-store"

        return response
